use handle_wait in pick behavior
ipa320/cob_robots pull request #411
Opened 2016-02-05 12:09 UTC by ipa-fxm

fixes https://github.com/ipa320/cob_robots/issues/387

needs to be tested on robot.

2016-02-05 12:14 UTC, ipa-fxm commented
Using `handle.wait()` allows for __safer__ execution, i.e. each motion needs to be successful before next motion start...abort with failure otherwise. 
However, the behavior now (might) look like stop-and-go.
For the case where fluent motion is required, I kept the `sleep()`-synchronization in comments. Simply bring it back in and comment out the "handle.wait-if-return" blocks...

2016-03-14 15:37 UTC, ipa-nhg commented
Already tested on the robot?

2016-03-14 18:08 UTC, ipa-fxm commented
No...as robot currently is mostly "armless"... :wink:

2017-01-19 15:43 UTC, ipa-fxm commented
@ipa-nhg please combine this PR with #591 in order to fix #387

2017-01-19 18:12 UTC, ipa-fxm commented
includes #591

2017-01-23 17:02 UTC, floweisshardt approved these changes

2017-01-23 17:49 UTC, floweisshardt requested changes

2017-01-23 17:49 UTC, ipa-fmw commented on cob_default_robot_behavior/scripts/trigger_srvs_cob4-7.py
> +    handle_base.wait()
error while testing on robot (`move_base_rel` does not support `.wait`)

```
[INFO] [WallTime: 1485193296.888138] Set <<mimic>> to <<['happy', 0, 1]>>
[INFO] [WallTime: 1485193296.989465] Move <<arm_left>> to <<side>>
[INFO] [WallTime: 1485193297.277909] Move <<arm_right>> to <<side>>
[INFO] [WallTime: 1485193297.604288] Wait for <<arm_left>> reaching <<side>>...
[INFO] [WallTime: 1485193297.604746] ...<<arm_left>> reached <<side>>
[INFO] [WallTime: 1485193297.605281] Wait for <<arm_right>> reaching <<side>>...
[INFO] [WallTime: 1485193297.705841] ...<<arm_right>> reached <<side>>
[INFO] [WallTime: 1485193297.706162] ------------------torso movement
[INFO] [WallTime: 1485193297.708325] Move <<torso>> to <<front_down_full>>
[INFO] [WallTime: 1485193297.962450] Move base relatively by <<[0, 0, 1.57]>>
[INFO] [WallTime: 1485193297.964314] Wait for <<torso>> reaching <<front_down_full>>...
[INFO] [WallTime: 1485193298.065064] ...<<torso>> reached <<front_down_full>>
[INFO] [WallTime: 1485193298.065414] Wait for <<base>> reaching <<[0, 0, 1.57]>>...
[ERROR] [WallTime: 1485193298.066156] Error processing request: 'NoneType' object has no attribute 'wait_for_result'
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/u/fmw/git/care-o-bot/src/cob_robots/cob_default_robot_behavior/scripts/trigger_srvs_cob4-7.py", line 109, in pick_cb\n    handle_base.wait()\n', '  File "/u/robot/git/care-o-bot/install/lib/python2.7/dist-packages/simple_script_server/simple_script_server.py", line 1220, in wait\n    self.wait_for_finished(duration,True)\n', '  File "/u/robot/git/care-o-bot/install/lib/python2.7/dist-packages/simple_script_server/simple_script_server.py", line 1251, in wait_for_finished\n    self.client.wait_for_result()\n', "AttributeError: 'NoneType' object has no attribute 'wait_for_result'\n"]
```

2017-01-23 18:03 UTC, ipa-fmw commented
sorry for creating a merge conflict again by merging #591

2017-01-23 21:05 UTC, ipa-fxm commented
I rebased...but don't know how to solve `move_base_rel`....
Even more, I think #591 has some issues, too - see https://github.com/ipa320/cob_robots/pull/591/files#r97415187

2017-01-23 21:28 UTC, ipa-fxm commented
How is this?
Could you test it again?
All behaviors are harmonized now...

2017-03-16 18:28 UTC, ipa-fxm commented
finally remove pick as it was never used again
-> #636

2017-03-16 18:28 UTC, closed without merging