raw3-6 bringup + ur10
ipa320/cob_robots pull request #536
Opened 2016-09-13 12:42 UTC by ipa-bnm

updated raw3-6 bringup + added ur10 to bringup

2016-09-15 08:03 UTC, ipa-fmw commented
Travis reports an error in the URDF. please fix

2016-09-15 08:04 UTC, ipa-fmw commented
just merged https://github.com/ipa320/cob_calibration_data/pull/104 and retriggered travis

2016-09-15 09:24 UTC, ipa-nhg commented on cob_bringup/robots/raw3-6.xml
> +		<include file="$(find ur_bringup)/launch/ur_common.launch">
This launch file includes also a robot_state_publisher node https://github.com/ros-industrial/universal_robot/blob/indigo-devel/ur_bringup/launch/ur_common.launch#L28 

`roslaunch file contains multiple nodes named [/robot_state_publisher]`

2016-09-15 09:26 UTC, NadiaHG requested changes

2016-09-15 10:46 UTC, ipa-bnm commented on cob_bringup/robots/raw3-6.xml
> +		<include file="$(find ur_bringup)/launch/ur_common.launch">
thx already fixed

2016-09-15 11:32 UTC, ipa-fmw commented
strange, but travis reports an issue about raw3-4:
```
[/home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/raw3-4.xml]:
	included file [/home/travis/catkin_ws/src/cob_robots/cob_bringup/drivers/ur.launch] requires the 'min_payload' arg to be set
```

2016-09-21 10:42 UTC, ipa-bnm commented
@ipa-nhg @ipa-fmw can someone please review / merge

2016-09-21 10:49 UTC, NadiaHG approved these changes
FR: OK

2016-09-21 11:21 UTC, merged