added env.sh plath as argument
ipa320/cob_robots pull request #537
Opened 2016-09-20 13:27 UTC by ipa-nhg

It is the same concept as https://github.com/ipa320/cob_robots/pull/462/files (thanks @ipa-fxm)

It is needed in case that you try to launch drivers on a remote machine sourcing a different workspace. For example if logged as nhg user I source `/u/otherUsergit/care-o-bot/devel/setup.bash` , and I command `roslaunch cob_bringup robot.launch` the machine tag will find my env.sh https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/env.sh and will set `MY_CATKIN_WORKSPACE` to `/u/nhg/git/care-o-bot/devel` ignoring the launch file the setup.bash that I sourced. 

If the user is able to set the env.sh path I can command `roslaunch cob_bringup cob4-1.launch env-script=/u/otherUsergit/care-o-bot/devel/env.sh` and I will run the packages from `/u/otherUsergit/care-o-bot/devel` wokspace.

2016-09-21 09:36 UTC, ipa-nhg commented
Test on cob4-1: OK

2016-09-21 10:54 UTC, benmaidel requested changes
please adopt this changes to the raw's as well

2016-09-21 14:31 UTC, ipa-nhg commented
@ip-bnm done!

2016-09-22 08:46 UTC, floweisshardt approved these changes

2016-09-22 08:47 UTC, ipa-fmw commented
@ipa-bnm please approve

2016-09-23 10:53 UTC, ipa-fmw commented
@ipa-bnm's comment is resolved, so accepting this PR

2016-09-23 10:54 UTC, merged