added back_left and back_right
ipa320/cob_robots pull request #554
Opened 2016-11-15 14:22 UTC by fmw-hb

needed for https://github.com/ipa320/ipa_navigation_planning/pull/128

2016-11-15 14:44 UTC, benmaidel requested changes

2016-11-15 14:44 UTC, ipa-bnm commented on cob_default_robot_config/cob4-2/torso_joint_configurations.yaml
> +back: [back_left]
is this really working?

2016-11-15 14:56 UTC, HannesBachter commented on cob_default_robot_config/cob4-2/torso_joint_configurations.yaml
> +back: [back_left]
have not tried that - will do

2016-11-15 15:03 UTC, fmw-hb commented on cob_default_robot_config/cob4-2/torso_joint_configurations.yaml
> +back: [back_left]
does work in simulation...

2016-11-15 15:03 UTC, fmw-hb commented
works in simulation

2016-11-15 18:07 UTC, floweisshardt commented on cob_default_robot_config/cob4-2/torso_joint_configurations.yaml
> +back: [back_left]
yes, this is a valid trajectory specification, see `nod` and `shake`

2016-11-15 18:08 UTC, floweisshardt approved these changes
CR: OK

2016-11-16 09:00 UTC, benmaidel approved these changes

2016-11-16 10:03 UTC, merged