Setup cob4-10
ipa320/cob_robots pull request #556
Opened 2016-11-18 13:09 UTC by ipa-nhg

2016-11-21 09:25 UTC, ipa-nhg commented
Please merge first the cob4-7 setup PR https://github.com/ipa320/cob_robots/pull/481

2016-12-07 16:17 UTC, ipa-fxm commented
rebase to get rid of ```cob4-7```-related commits

2016-12-09 10:12 UTC, fmessmer requested changes
rebase to get rid of ```cob4-7```-related commits and merge-conflicts

2016-12-13 16:55 UTC, ipa-fxm commented on cob_hardware_config/cob4-10/config/teleop.yaml
> +#cob4-7
```#cob4-10```

2016-12-13 16:55 UTC, ipa-fxm commented on cob_hardware_config/cob4-10/urdf/cob4-10.urdf.xacro
> +       name="cob4-7" >
```cob4-10```

2016-12-19 09:24 UTC, ipa-nhg commented on cob_hardware_config/cob4-10/config/teleop.yaml
> +#cob4-7
done!

2016-12-19 09:24 UTC, ipa-nhg commented on cob_hardware_config/cob4-10/urdf/cob4-10.urdf.xacro
> +       name="cob4-7" >
done!

2017-01-11 08:44 UTC, fmessmer approved these changes

2017-01-11 08:44 UTC, ipa-fxm commented
I'm going to squash this PR into a single commit...

2017-01-11 08:45 UTC, merged