coupled sensorring and head in one instance
ipa320/cob_robots pull request #561
Opened 2016-12-08 16:27 UTC by ipa-mdl

merged sensorring config into head config, added remaps and relays.

2016-12-08 16:41 UTC, ipa-nhg commented
@ipa-mdl tested on the robot?

2016-12-08 16:44 UTC, ipa-mdl commented
The spawner does not work very well if spawning fails for some reason.
Perhaps we should implements a service relay with controller spawning..

2016-12-08 16:45 UTC, ipa-mdl commented
> tested on the robot

I was able to move the sensorring ;)

2016-12-08 17:14 UTC, ipa-mdl commented
Perhaps with should substitute with https://github.com/ipa320/cob_control/pull/118

2016-12-09 07:52 UTC, fmessmer requested changes

2016-12-09 07:52 UTC, ipa-fxm commented on cob_bringup/package.xml
> +  <exec_depend>service_tools</exec_depend>
pedantic: keep alphabetic order :wink:

2016-12-09 07:54 UTC, ipa-fxm commented on cob_bringup/robots/cob4-10.xml
> +        <remap from="/head/sensorring_joint_trajectory_controller/follow_joint_trajectory" to="/sensorring/joint_trajectory_controller/follow_joint_trajectory"/>
why is this magic needed?

2016-12-09 07:55 UTC, ipa-fxm commented on cob_hardware_config/cob4-10/config/joint_state_publisher.yaml
> +source_list: [/base/joint_states, /torso/joint_states, /head/joint_states]
if you keep the ```sensorring/joint_states``` here, you would not need the topic_relay, right?

2016-12-09 07:57 UTC, fmessmer requested changes

2016-12-09 07:57 UTC, ipa-fxm commented on cob_bringup/robots/cob4-10.xml
> +	          <node name="sensorring_switch_relay" pkg="service_tools" type="service_relay" args="controller_manager/switch_controller /head/controller_manager/switcj_controller" respawn="false" output=
typo: switcj -> switch

2016-12-09 08:58 UTC, mathias-luedtke commented on cob_bringup/package.xml
> +  <exec_depend>service_tools</exec_depend>
Again? ;)
At least I hit the S range :D

2016-12-09 09:00 UTC, ipa-mdl commented on cob_bringup/robots/cob4-10.xml
> +        <remap from="/head/sensorring_joint_trajectory_controller/follow_joint_trajectory" to="/sensorring/joint_trajectory_controller/follow_joint_trajectory"/>
This relocates the sensorring trajectory controller (spawned in head driver) into the sensorring namespace

2016-12-09 09:02 UTC, ipa-mdl commented on cob_hardware_config/cob4-10/config/joint_state_publisher.yaml
> +source_list: [/base/joint_states, /torso/joint_states, /head/joint_states]
`/head/joint_states` contains head+sensorring.
The relay is needed just for the script server, which expects them in sensorring as well.

2016-12-09 09:04 UTC, mathias-luedtke commented on cob_bringup/robots/cob4-10.xml
> +        <remap from="/head/sensorring_joint_trajectory_controller/follow_joint_trajectory" to="/sensorring/joint_trajectory_controller/follow_joint_trajectory"/>
The sensorring will almost look like all other component namespaces..

2016-12-09 09:16 UTC, mathias-luedtke commented on cob_bringup/package.xml
> -  <exec_depend>sick_visionary_t_driver</exec_depend>
this went wrong, will push it into the first commit

2016-12-09 09:37 UTC, ipa-mdl commented
Fixed the typo and sorting.

Please note, I have not tested the last commit on the robot.

2016-12-09 10:07 UTC, fmessmer approved these changes

2016-12-09 10:08 UTC, ipa-fxm commented
Will we need to apply these changes to cob4-7, too?
Let's also wait for travis and a "Tested on robot: OK"

2016-12-09 10:28 UTC, ipa-nhg commented
Still not working on the robot something with the namespaces is  wrong, after init I have the topics:

/head/joint_group_position_controller/command
/head/joint_group_velocity_controller/command
/head/joint_states
/head/joint_trajectory_controller/command
/head/joint_trajectory_controller/follow_joint_trajectory/cancel
/head/joint_trajectory_controller/follow_joint_trajectory/feedback
/head/joint_trajectory_controller/follow_joint_trajectory/goal
/head/joint_trajectory_controller/follow_joint_trajectory/result
/head/joint_trajectory_controller/follow_joint_trajectory/status
/head/joint_trajectory_controller/state
**/head/sensorring_joint_trajectory_controller/command
/head/sensorring_joint_trajectory_controller/state**

And 

/sensorring/joint_states
/sensorring/joint_trajectory_controller/follow_joint_trajectory/cancel
/sensorring/joint_trajectory_controller/follow_joint_trajectory/feedback
/sensorring/joint_trajectory_controller/follow_joint_trajectory/goal
/sensorring/joint_trajectory_controller/follow_joint_trajectory/result
/sensorring/joint_trajectory_controller/follow_joint_trajectory/status

and `rosservice call /head/controller_manager/list_controllers` says:

```
controller: 
  - 
    name: joint_trajectory_controller
    state: running
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['head_2_joint', 'head_3_joint']
  - 
    name: joint_state_controller
    state: running
    type: joint_state_controller/JointStateController
    hardware_interface: hardware_interface::JointStateInterface
    resources: []
  - 
    name: sensorring_joint_trajectory_controller
    state: running
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['sensorring_joint']
  - 
    name: joint_group_position_controller
    state: stopped
    type: position_controllers/JointGroupPositionController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['head_2_joint', 'head_3_joint']
  - 
    name: joint_group_velocity_controller
    state: stopped
    type: velocity_controllers/JointGroupVelocityController
    hardware_interface: hardware_interface::VelocityJointInterface
    resources: ['head_2_joint', 'head_3_joint']
```

If I send a trajectory I see that I sending a command to /head/joint_trajectory_controller/command but the actuator doesn't move.

Tested with https://github.com/ipa320/cob_command_tools/pull/164 and https://github.com/ipa320/cob_control/pull/118.

@ipa-fxm I would like to wait until it is working before merge the config for the other robots, actually cob4-1, cob4-2, cob4-7, cob4-10 and soon cob4-5 should use this head/sensorring configuration.

2016-12-09 10:35 UTC, ipa-mdl commented
The topics are fine!
`/head/sensorring_joint_trajectory_controller/command` is used by rqt only and it expects it in the controller's namespace.
Not sure about `/head/sensorring_joint_trajectory_controller/state`, we don't use it anyway (?).

Head does not move right now since the motors cannot be started( check diagnostics, @ipa-tif needs to fix this).

2016-12-09 10:41 UTC, ipa-mdl commented
Before merging it for the other robots, the head+sensorring combo should be factored out into a separate launch file.
It would be better to actually split the controller config again and upload both.

2016-12-09 11:33 UTC, ipa-mdl commented
where to put such a launch file?

2016-12-09 11:43 UTC, ipa-mdl commented
rebased to keep the sensorring_controller.yaml (used with gazebo)

2016-12-09 12:09 UTC, ipa-fxm commented
> where to put such a launch file?

As it only launches controller-related things, I'd put it into cob_bringup/controllers.

2016-12-09 12:35 UTC, ipa-mdl commented
> As it only launches controller-related things

It launches as driver and set-ups the controllers, i.e. `head_sensorring.xml`.

2017-01-11 10:43 UTC, closed without merging