added external sync mode and shared config for head and sensorrring
ipa320/cob_robots pull request #568
Opened 2016-12-13 16:25 UTC by ipa-mdl

This config sets up an external sync (needs https://github.com/ros-industrial/ros_canopen/pull/201) from a shared config.

alternative to #566

2016-12-14 16:03 UTC, ipa-mdl commented
This is my preferred solution.

2016-12-16 10:52 UTC, fmessmer requested changes
Travis fails:

```
-------------------------------------------------

Full test results for 'build/test_results/cob_bringup/roslaunch-check_cob4-1__ROBOT_ENV_ipa-kitchen.xml.xml'

-------------------------------------------------

<?xml version="1.0" encoding="UTF-8"?>

<testsuite tests="1" failures="1" time="1" errors="0" name="roslaunch-check_cob4-1__ROBOT_ENV_ipa-kitchen.xml.xml">

  <testcase name="test_ran" status="run" time="1" classname="Results">

  <failure message="roslaunch check [/home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob4-1.xml] failed" type=""/>

  </testcase>

  <system-out><![CDATA[[

[/home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob4-1.xml]:

	Missing package dependencies: cob_bringup/package.xml: canopen_chain_node

cannot find node [canopen_sync_node] in package [canopen_chain_node]

]]></system-out>

</testsuite>
```

2016-12-16 10:53 UTC, fmessmer requested changes
Travis fails:

```
-------------------------------------------------

Full test results for 'build/test_results/cob_bringup/roslaunch-check_cob4-1__ROBOT_ENV_ipa-kitchen.xml.xml'

-------------------------------------------------

<?xml version="1.0" encoding="UTF-8"?>

<testsuite tests="1" failures="1" time="1" errors="0" name="roslaunch-check_cob4-1__ROBOT_ENV_ipa-kitchen.xml.xml">

  <testcase name="test_ran" status="run" time="1" classname="Results">

  <failure message="roslaunch check [/home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob4-1.xml] failed" type=""/>

  </testcase>

  <system-out><![CDATA[[

[/home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob4-1.xml]:

	Missing package dependencies: cob_bringup/package.xml: canopen_chain_node

cannot find node [canopen_sync_node] in package [canopen_chain_node]

]]></system-out>

</testsuite>
```

2016-12-16 10:53 UTC, ipa-fxm commented on cob_bringup/drivers/canopen_402.launch
> +	<node pkg="canopen_chain_node" type="canopen_sync_node" name="sync_$(arg can_device)_$(arg component_name)" output="screen" if="$(arg start_external_sync)">
please add dependency to  ```canopen_chain_node``` to cob_bringup/package.xml

2016-12-16 11:45 UTC, mathias-luedtke commented on cob_bringup/drivers/canopen_402.launch
> +	<node pkg="canopen_chain_node" type="canopen_sync_node" name="sync_$(arg can_device)_$(arg component_name)" output="screen" if="$(arg start_external_sync)">
(`canopen_chain_node` is a dependency of `canopen_motor_node` thus)
`canopen_sync_node` will be available with https://github.com/ros-industrial/ros_canopen/pull/201)

2016-12-16 13:39 UTC, ipa-mdl commented
added dependency.

2016-12-16 13:44 UTC, fmessmer approved these changes

2016-12-16 13:44 UTC, ipa-fxm commented on cob_bringup/drivers/canopen_402.launch
> +	<node pkg="canopen_chain_node" type="canopen_sync_node" name="sync_$(arg can_device)_$(arg component_name)" output="screen" if="$(arg start_external_sync)">
https://github.com/ipa320/cob_robots/pull/568/files#diff-cca74cba52fdd3b91eb2f4a7e4b67816R19

2016-12-16 14:03 UTC, ipa-mdl commented
2d90eb018304206f7c91c9b2f8f2c43bc089e717 should be reverted later:
* remove can settings from config files
* set sync rate in launch file

In addition `use_external_sync=true` should become the new default.

2017-01-11 10:38 UTC, ipa-fxm commented
I'm trying to understand which of the related PRs are still relevant...
It seems that this PR replaces #561 and #566...is this correct?
Any changes from one of those PRs that needs to be added to this one?
What about [your comment](https://github.com/ipa320/cob_robots/pull/568#issuecomment-267600358)? Can this be finalized?
I guess travis fails because latest ros_canopen (including external sync) is not yet released....

2017-01-11 11:42 UTC, ipa-mdl commented
I have closed the others PRs.
My comment should become a new issue to keept track of it.

> I guess travis fails because latest ros_canopen (including external sync) is not yet released....

It is not released as it should be tested a little bit longer ;)
Just keep me posted for planned `cob_robots` releases.

2017-01-19 15:38 UTC, ipa-fxm commented
@ipa-mdl @ipa-nhg 
So do we need this for cob4-10/cob4-7? 
If we do not merge this how are head and sensorring actuated on hardware?

2017-01-20 07:49 UTC, ipa-fmw commented
included in https://github.com/ipa320/cob_robots/pull/593 which was tested successfully on cob4-7/cob4-10

2017-01-20 08:33 UTC, ipa-fxm commented
I put a note about high load problem caused by the `cartesian_control` [here](https://github.com/ipa320/cob_control/issues/101#issuecomment-274008953)...will work on this as soon as I find the time

2017-01-20 15:49 UTC, merged