move cob_moveit_config
ipa320/cob_robots pull request #573
Opened 2016-12-16 10:15 UTC by ipa-fxm

as discussed here https://github.com/ipa320/cob_manipulation/pull/88#issuecomment-267271654

2016-12-16 12:41 UTC, mathias-luedtke requested changes
versions need to be updated to 0.6.6

2016-12-16 12:41 UTC, ipa-mdl commented on cob_robots/package.xml
> +  <exec_depend>cob_default_robot_behavior</exec_depend>
this one slipped through

2016-12-16 13:04 UTC, ipa-fxm commented
version adjusted...and adding cob_default_robot_behavior in separate commit :wink:

2016-12-16 13:13 UTC, ipa-mdl commented
> version adjusted...
 Not sure if Changelog needs to be update as well

> and adding cob_default_robot_behavior in separate commit 
 but.. ;)

2016-12-16 13:38 UTC, mathias-luedtke approved these changes

2016-12-19 10:58 UTC, NadiaHG requested changes

2016-12-19 10:58 UTC, ipa-nhg commented on cob_moveit_config/package.xml
> +  <exec_depend>moveit_setup_assistant</exec_depend>
I don't like this dependency... That means that cob_bringup depends on moveit_core, moveit_ros_planning and moveit_ros_visualization... @ipa-mdl @ipa-fxm could be `cob_moveit_config/launch/setup_assistant.launch`  moved to **cob_moveit_bringup**??

2016-12-19 10:58 UTC, ipa-nhg commented on cob_moveit_config/CMakeLists.txt
> +    cob4-7
add please cob4-5, and also the folder required!

2016-12-19 11:46 UTC, ipa-mdl commented on cob_moveit_config/package.xml
> +  <exec_depend>moveit_setup_assistant</exec_depend>
This line does not belong here.

2016-12-19 11:47 UTC, ipa-mdl commented on cob_moveit_config/CMakeLists.txt
> +    cob4-7
Perhaps we can just glob all folders..

2017-01-11 08:23 UTC, ipa-fxm commented on cob_moveit_config/CMakeLists.txt
> +    cob4-7
We will deal with this in #577 as it can be applied in various packages....

2017-01-11 08:30 UTC, ipa-fxm commented on cob_moveit_config/package.xml
> +  <exec_depend>moveit_setup_assistant</exec_depend>
done in https://github.com/ipa320/cob_robots/pull/573/commits/4c9013ca2914748a9082036f83db016c4e6c1064 and https://github.com/ipa320/cob_manipulation/pull/91/commits/5d4c095891612ca137be2f357f4f66b678d81623

2017-01-11 12:03 UTC, ipa-fxm commented on cob_moveit_config/CMakeLists.txt
> +    cob4-7
will do this in a new PR when I update all moveit_configs according to latest cob_hardware_config...also including the new mesh https://github.com/ipa320/cob_manipulation/issues/89

2017-01-11 12:25 UTC, merged