Use grouped low level components for simulation
ipa320/cob_robots pull request #583
Opened 2017-01-11 19:46 UTC by ipa-fxm

builds on top of #575 
I then introduced a ```sim``` launch-argument and made use of it in ```cob_bringup/robot.xml```

There I followed the scheme:
Within each ```machine```-tag:
 - first there is a hardware-specific ```group unless="$(arg sim)"```, where hardware specific nodes are started
 - followed by a block of "togglable" component launch files where the ```sim``` argument is passed
 - ending in a block of nodes that can be used __identically__ within hardware and simulation

Afterwards I removed from ```cob_configuration_controller_gazebo/default_controllers_robot.launch``` all the parts that are now covered by the new robot.xml file. What is left there is simulation-specific.

To use this in simulation https://github.com/ipa320/cob_simulation/pull/131 is required

2017-01-12 14:16 UTC, ipa-fxm commented
grouping legacy components and applying new structure for cob3-2

2017-01-12 14:17 UTC, ipa-fxm commented
@ipa-mdl @ipa-fmw @ipa-nhg @ipa-bnm @ipa-mig feedback welcome!

2017-01-12 18:40 UTC, ipa-fxm commented
Still missing are the raw's
I also will compare ```rosnode list```, ```rostopic list```, ```rosservice list``` and ```rosparam list``` of simulation (indigo_dev vs. feature_branch) as well as simulation vs. hardware (where possible) in order to see whether I missed something.

Still, feel free to drop in feedback already!

2017-01-13 07:31 UTC, mgruhler requested changes
Getting impatient? ;-)

I like this. Seems to reduce a lot of duplication.

(Note that I did not check all robot specific launch and xml files for now)

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/components/legacy_base.launch
> +			<arg name="odom_topic"			default="odometry_controller/odometry"/>
mixed tabs and spaces

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/components/cob4_head_camera.launch
> +   <include unless="$(arg sim)" file="$(find cob_bringup)/drivers/usb_camera_node.launch">
tabs vs spaces

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/components/cob4_head_camera.launch
> +		</include>
2 tabs

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/components/legacy_schunk_powercube.launch
> +		</include>
tabs vs spaces

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/components/legacy_schunk_powercube.launch
> +		<include file="$(find cob_bringup)/controllers/cob_trajectory_controller.launch">
imo, it would improve readability to add an empty line between includes. what do you think?

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/robots/base_solo.launch
> +	</include>
shouldn't the `group` block below be exchanged with the `legacy_base.launch` file`?

2017-01-13 07:31 UTC, ipa-mig commented on cob_bringup/robots/cob3-6.xml
> +			</include-->
Is there a reason to comment out the `wifi_monitor`?

2017-01-13 09:28 UTC, ipa-mdl commented
> I also will compare rosnode list, rostopic list, rosservice list and rosparam list of simulation (indigo_dev vs. feature_branch) as well as simulation vs. hardware (where possible) in order to see whether I missed something.

Please try:
https://gist.github.com/ipa-mdl/66b14a895e13003a2f76e483bd00aa63

2017-01-13 09:34 UTC, ipa-fxm commented
@ipa-mdl, I tried to figure out how to use your script...can you give a usage example?

2017-01-13 09:38 UTC, ipa-mdl commented
>  I tried to figure out how to use your script...can you give a usage example?

like you would run `roslaunch`..
`./roslaunch-dump cob_robots cob4-2.launch`
(`chmod +x roslaunch-dump` first)

2017-01-13 09:55 UTC, ipa-mdl commented
The script does not handle `arg` tags for now, will fix it.

2017-01-13 17:39 UTC, ipa-fxm commented
For travis to be happy, https://github.com/ipa320/cob_common/pull/202 is required

I consider this restructuring done....for now...more iterations will follow...
I guaranteed the exact same behavior of the hardware (to the best of my knowledge and belief) using @ipa-mdl's [roslaunch-dump](https://gist.github.com/ipa-mdl/66b14a895e13003a2f76e483bd00aa63)

Simulation is working for all robots and basic functionality tests (move around using dashboard) were successful

2017-01-13 20:47 UTC, ipa-fxm commented
In future PRs
 - sort nodes/includes (alphabetically?) so that inter-robot comparison is easier
 - harmonize robots, i.e. converge xml's again
 - further group frequently used stuff, e.g. teleop, script_server,....into a command_tools.launch
 - move `cob_controller_configuration_gazebo` package to `cob_simulation`, then introduce "cob_bringup"-like structure within `cob_bringup_sim`, finally getting rid of `cob_controller_configuartion_gazebo` package

...amongst other things...tbd

2017-01-13 22:46 UTC, mathias-luedtke requested changes

2017-01-13 22:46 UTC, ipa-mdl commented on cob_bringup/components/cob4_head_camera.launch
> +   <include unless="$(arg sim)" file="$(find cob_bringup)/drivers/usb_camera_node.launch">
alignment was wrong

2017-01-13 22:46 UTC, ipa-mdl commented on cob_bringup/components/cam3d_r200_rgbd.launch
> +		<arg name="num_worker_threads" default="$(arg num_worker_threads)" />
default -> value?

2017-01-13 22:50 UTC, mathias-luedtke approved these changes
the woes of commit-based review ;)

2017-01-13 22:57 UTC, ipa-fxm commented on cob_bringup/components/cam3d_r200_rgbd.launch
> +		<arg name="num_worker_threads" default="$(arg num_worker_threads)" />
copy-paste...:wink:

2017-01-17 11:52 UTC, floweisshardt requested changes

2017-01-17 11:52 UTC, ipa-fmw commented on cob_bringup/components/cam3d_r200_rgbd.launch
> +	<include file="$(find cob_bringup)/drivers/image_flip_nodelet.launch">
use `flip` argument

2017-01-17 11:52 UTC, ipa-fmw commented on cob_bringup/components/cob4_head_camera.launch
> +	<include file="$(find cob_bringup)/drivers/image_flip.launch">
use `flip` argument

2017-01-17 13:43 UTC, floweisshardt approved these changes

2017-01-17 16:07 UTC, mgruhler approved these changes

2017-01-17 17:07 UTC, ipa-fxm commented
Will be rebased and squash-merged **after** https://github.com/ipa320/cob_robots/pull/585 and **updated** https://github.com/ipa320/cob_robots/pull/579 (by @ipa-mdl)

2017-01-18 10:03 UTC, ipa-fxm commented
I rebased this feature branch on top of `indigo_dev` as #579 and #585 have been merged now.
@ipa-fmw @ipa-nhg @ipa-mdl please one final review...
...and then this PR should be **Squash and merge** into a single commit e.g. "group components and restructure"

2017-01-18 13:05 UTC, merged

2017-01-18 13:11 UTC, ipa-fxm commented
tag [eol-cob3](https://github.com/ipa320/cob_robots/tree/eol-cob3) has been added