Update behavior script to move the arms for cob4-7
ipa320/cob_robots pull request #591
Opened 2017-01-19 10:24 UTC by ipa-nhg

2017-01-19 11:41 UTC, ipa-fxm commented
can you combine this with #411 and either pull them in or close?
related to https://github.com/ipa320/cob_robots/issues/387

2017-01-19 15:31 UTC, fmessmer requested changes
can you combine this with #411 and either pull them in or close?
related to https://github.com/ipa320/cob_robots/issues/387

2017-01-19 16:24 UTC, ipa-nhg commented
why?  they are two different things.... and different files. This pull request implements the **torso_front_cb behavior** for cob4-7, it is already tested on the robot and works. 

The https://github.com/ipa320/cob_robots/pull/411/files use handles for the **pick behavior** and it is still not tested.

2017-01-19 16:48 UTC, ipa-fxm commented
Well, IMHO it is related and I am trying to close old PRs and Issues...so if we test pick on cob4-7, we could also add it to cob4-2...it's all about keeping similar robots similar

2017-01-23 17:56 UTC, floweisshardt approved these changes
tested on cob4-7: OK

2017-01-23 17:56 UTC, ipa-fmw commented
merging this one as #411 still has issues.

2017-01-23 17:56 UTC, merged

2017-01-23 21:03 UTC, ipa-fxm commented on cob_default_robot_behavior/scripts/trigger_srvs_cob4-7.py
> +        sss.move("torso","front_down_full",True)
Well, then this condition is not safe, too, as we do not check whether `sss.move("torso", ...)` was correct....we simply `return TriggerResponse(True, "")`