Raw order picking config
ipa320/cob_robots pull request #601
Opened 2017-01-25 09:10 UTC by ipa-bfb

Actual configuration of RAW with UR arm

2017-01-25 09:29 UTC, ipa-fxm commented
This has a merge conflict...as we did some bigger restructuring in cob_robots...please merge with latest cob_robots/indigo_dev, adjust accordingly and test updated branch on robot..

2017-01-26 19:47 UTC, ipa-fxm commented
Your merge didn't go well....there is file which are already merged into ipa320/indigo_dev and you commited a lot of temp files from merge conflicts, e.g. *.orig or *.BACKUP.*, *.BASE.*, *.LOCAL.*

2017-02-14 09:56 UTC, ipa-bfb commented
The masses of the UR10 arm should be reduced in order to get a stable simulation. The robot configuration  is now fine.

2017-02-14 13:40 UTC, ipa-fxm commented
Has this been tested again with hardware?

2017-02-14 13:49 UTC, fmessmer commented
> The masses of the UR10 arm should be reduced in order to get a stable simulation. The robot configuration is now fine.

Can you try [this](https://github.com/ipa320/cob_common/pull/207#issuecomment-279710744) tweaking the base mass/inertia so that we do not rely on modified `ur_description`?

2017-02-14 16:16 UTC, ipa-bfb commented
Done. I icreased the batery mass to 50 kg and it worked

2017-02-15 09:53 UTC, fmessmer requested changes

2017-02-15 09:53 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/config/arm_controller.yaml
> +  type: velocity_controllers/JointGroupVelocityController
note that currently [ur_description](https://github.com/ros-industrial/universal_robot/blob/indigo-devel/ur_description/urdf/ur.transmission.xacro) only supports `JointPositionInterface`, i.e. `position_controllers`

2017-02-15 09:53 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/config/arm_self_collision.yaml
> +    ##head_3_link : [arm_left_3_link, arm_left_4_link, arm_left_5_link, arm_left_6_link, arm_left_7_link],
leave file empty...or set proper link_names...but those commented are not available on raw3-1 with ur....

2017-02-15 09:53 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/urdf/raw3-1.urdf.xacro
> +  <xacro:vacuum_gripper_definition name="gripper" parent="arm_ee_link" prefix="${arm_prefix}">
macro name has changed in cob_common....`vacuum_gripper`....

2017-02-15 09:53 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/urdf/raw3-1.urdf.xacro
> +  <xacro:vacuum_gripper_definition name="gripper" parent="arm_ee_link" prefix="${arm_prefix}">
`prefix` parameter has been removed...

2017-02-15 09:53 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/urdf/raw3-1.urdf.xacro
> +  </xacro:vacuum_gripper_definition>
macro name!

2017-02-15 10:31 UTC, ipa-bfb commented on cob_hardware_config/raw3-1/config/arm_controller.yaml
> +  type: velocity_controllers/JointGroupVelocityController
Sorry I think i mix this with other branch. I'm going to test the new driver to use velocity control for this arm but I will submit this if this works in a future pull request.

2017-02-16 08:23 UTC, fmessmer requested changes
And I see the following warnings:
 > [ WARN] [1487232228.326437512]: Parameter 'devicedriver' is missing. Using default Value: cob_ledboard

 > [ WARN] [1487232228.471580320]: Parameter 'num_leds' is missing. Using default Value: 58

2017-02-16 08:23 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/config/arm_cartesian_controller.yaml
> +## Cartesian controller parameters
so this file should be removed from this PR, then

2017-02-16 08:23 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/config/arm_controller.yaml
> +## position controller
these also won't work with the real hardware

2017-02-16 08:23 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/config/arm_self_collision.yaml
> +    ##head_3_link : [arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_elbow_joint, arm_wrist_1_joint, arm_wrist_2_joint, arm_wrist_3_joint],
there is no `head_3_link` on raw3-1

2017-02-16 08:23 UTC, ipa-fxm commented on cob_moveit_config/raw3-1/config/ompl_planning.yaml
>  planner_configs:
did you also update the SRDF?
you can use `rosrun cob_moveit_bringup update_collisions.sh raw3-1` to update the self-collision matrix
please also update the planning groups!

2017-02-16 08:54 UTC, ipa-bfb commented on cob_moveit_config/raw3-1/config/ompl_planning.yaml
>  planner_configs:
Well this was updated and tested from the vision fair. So it should still be updated if this configuration was not lost with all these last changes in the repository.

2017-02-16 09:04 UTC, ipa-bfb commented
I have no idea how to fix these warning. Do you?

2017-02-16 12:29 UTC, ipa-fxm commented on cob_hardware_config/raw3-1/config/light.yaml
> +invert_output: false
@ipa-bnm 
Could you please have a look at this yaml?
We used the layout from raw3-3...do you know what value to set for `devicedriver`, `baudrate` and `num_leds` for raw3-1?

2017-02-16 12:33 UTC, fmessmer approved these changes

2017-02-16 15:55 UTC, ipa-fxm commented
@ipa-bfb 
I had to comment the `ur_modern_driver` part in https://github.com/ipa320/cob_robots/pull/601/commits/115c020ff201206dfd081e793505cea2c842e0a3 in order to pass the CI-Tests...
We will need to deal with this in a separate PR when you  did further tests...

2017-02-16 16:31 UTC, ipa-bfb commented
Sure ;)

2017-02-20 11:44 UTC, merged