added fake power state publisher in order to support simulation
ipa320/cob_robots pull request #610
Opened 2017-02-02 15:34 UTC by souravran

2017-02-02 16:22 UTC, fmessmer requested changes
some changes requested

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +    <arg name="sim" default="$(arg sim)"/>
default should be `false`

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +    <node if="$(arg sim)" pkg="rostopic" type="rostopic" args="pub /power_state cob_msgs/PowerState '{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, voltage: 0.0, current: 0.0, power_con
we used tabs as indentation in all the cob_bringup launch files...

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/drivers/sick_flexisoft.launch
> +	<arg name="sim" default="$(arg sim)"/>
default should be `false`

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +    </node>
I guess the two nodes above are `unless="$(arg sim)"` as they are not used in simulation, right? Put them in an `unless` `group`

Keep an empty line to the next `if="$(arg sim)"` for clearer structure

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-10.xml
> +			<arg name="robot" value="$(arg robot)"/>
now that `bms.launch` can take the `sim` arg, you need to pass it!

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-2.xml
> +    <machine name="cob4-2-b1" address="$(arg cob4-2-b1)" env-loader="$(arg env-script)" default="true" timeout="30"/>
keep indentation as it has been - use tabs!

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-3.xml
> +        </include>
keep indentation as it has been - use tabs!

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-4.xml
> +    </group>
keep indentation as it has been - use tabs!

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-5.xml
> +    <machine name="cob4-5-b1" address="$(arg cob4-5-b1)" env-loader="$(arg env-script)" default="true" timeout="30"/>
keep indentation as it has been - use tabs!

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-6.xml
> +    <machine name="cob4-6-b1" address="$(arg cob4-6-b1)" env-loader="$(arg env-script)" default="true"/>
keep indentation as it has been - use tabs!

2017-02-02 16:22 UTC, ipa-fxm commented on cob_bringup/robots/cob4-7.xml
> +			<arg name="robot" value="$(arg robot)"/>
pass `sim` argument

2017-02-02 16:25 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +    <node if="$(arg sim)" pkg="rostopic" type="rostopic" args="pub /power_state cob_msgs/PowerState '{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, voltage: 0.0, current: 0.0, power_con
@souravran did you already implement the script publishing the `/power_state` topic through a [Timer](http://wiki.ros.org/rospy/Overview/Time#Timer) where it provides the two services `set_remaining_capacity` (`cob_srvs/SetFloat`) and `set_charging` (`std_srvs/SetBool`)?

2017-02-02 16:26 UTC, fmessmer reviewed
Question

2017-02-02 16:26 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +    <node if="$(arg sim)" pkg="rostopic" type="rostopic" args="pub /power_state cob_msgs/PowerState '{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, voltage: 0.0, current: 0.0, power_con
@souravran did you already implement the script publishing the `/power_state` topic through a [Timer](http://wiki.ros.org/rospy/Overview/Time#Timer) where it provides the two services `set_remaining_capacity` (`cob_srvs/SetFloat`) and `set_charging` (`std_srvs/SetBool`)?

2017-02-02 17:33 UTC, souravran commented on cob_bringup/drivers/bms.launch
> +    <node if="$(arg sim)" pkg="rostopic" type="rostopic" args="pub /power_state cob_msgs/PowerState '{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, voltage: 0.0, current: 0.0, power_con
Have not done that yet, I will implement the script for these two services and update the pull request.

2017-02-03 08:32 UTC, fmessmer requested changes
still some issues with indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +    <node if="$(arg sim)" pkg="rostopic" type="rostopic" args="pub /power_state cob_msgs/PowerState '{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, voltage: 0.0, current: 0.0, power_con
use tabs for indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-10.xml
> +            <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-2.xml
> +            <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-3.xml
> +                <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-4.xml
> +                <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-4.xml
> +            <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-5.xml
> +            <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-6.xml
> +                <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-6.xml
>  			</include>
also, since bms.launch now has the `flag`, it can be moved out of the `<group unless="$(arg sim)">`

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-7.xml
> +            <arg name="sim" value="$(arg sim)"/>
indentation

2017-02-03 08:32 UTC, ipa-fxm commented on cob_bringup/robots/cob4-4.xml
>  			</include>
also, since bms.launch now has the `flag`, it can be moved out of the `<group unless="$(arg sim)">`

2017-02-03 12:32 UTC, fmessmer approved these changes

2017-02-03 12:33 UTC, merged