incorporated changes to handle fake_bms and simulation
ipa320/cob_robots pull request #613
Opened 2017-02-08 08:09 UTC by souravran

2017-02-08 08:15 UTC, ipa-fxm commented
requires https://github.com/ipa320/cob_driver/pull/310

2017-02-09 17:36 UTC, fmessmer requested changes

2017-02-09 17:36 UTC, ipa-fxm commented on cob_bringup/drivers/bms.launch
> +	<rosparam command="load" file="$(arg pkg_hardware_config)/$(arg robot)/config/bms.yaml" ns="bms"/>
Are you sure this works?
The `bms_driver_node` expects the parameters to be private...thus, I'd like to keep
```
<node unless="$(arg sim)" name="bms" pkg="cob_bms_driver" type="bms_driver_node" output="screen" clear_params="true">
	<rosparam command="load" file="$(arg pkg_hardware_config)/$(arg robot)/config/bms.yaml"/>
</node>
```

2017-02-14 14:17 UTC, floweisshardt approved these changes

2017-02-14 16:47 UTC, fmessmer approved these changes
I finalized it together with @souravran

2017-02-15 08:39 UTC, floweisshardt approved these changes

2017-02-15 09:23 UTC, merged