added stuck_detector to bringup
ipa320/cob_robots pull request #618
Opened 2017-02-10 20:03 UTC by ipa-bnm

2017-02-10 20:08 UTC, floweisshardt approved these changes

2017-02-13 08:30 UTC, fmessmer reviewed
do we also need this for the other robots?

2017-02-14 10:15 UTC, ipa-nhg commented on cob_bringup/robots/cob4-2.xml
> +                        <include file="$(find cob_omni_drive_controller)/launch/stuck_detector.launch">
could be the stuck_detector.launch file moved/copied to cob_bringup/drivers? For the consistency of cob_bringup..

2017-02-14 13:58 UTC, ipa-fmw commented
@ipa-fxm: this is rather one of the workarounds for https://github.com/ipa320/msh/issues/594. If this is solved properly, we can undo that again as it just adds another node and produces topic trafic. So it's ok to only have it in the 24/7 operated robots

2017-02-14 14:13 UTC, fmessmer requested changes
and I :+1: @ipa-nhg's request of moving the launch file to cob_bringup!

2017-02-14 14:14 UTC, fmessmer requested changes
and I :+1: @ipa-nhg's request of moving the launch file to cob_bringup!

2017-02-14 14:14 UTC, ipa-fxm commented on cob_bringup/robots/cob4-2.xml
> +                        </include>
tabs vs. spaces!

2017-02-16 10:39 UTC, ipa-bnm commented on cob_bringup/robots/cob4-2.xml
> +                        <include file="$(find cob_omni_drive_controller)/launch/stuck_detector.launch">
Copy :+1: Move :-1: 
If we move the launch file we will always need cob_robots (with thousands of deps) if we like to start the `stuck_detector`

2017-02-18 17:09 UTC, ipa-fxm commented
> do we also need this for the other robots?

stuck detector is added to all "canopen base" robots in #622

2017-02-20 10:57 UTC, ipa-nhg commented on cob_bringup/robots/cob4-2.xml
> +                        <include file="$(find cob_omni_drive_controller)/launch/stuck_detector.launch">
copy is also ok for me!

2017-02-20 11:39 UTC, ipa-bnm commented
@ipa-fxm no need to add it to all "canopen based" robots. Please see @ipa-fmw comment!

2017-02-21 05:52 UTC, ipa-fxm commented
in #622, @ipa-mdl did a significant unification of launch and configuration files...
stuck detector is now part of the unified [`cob4_base.launch`](https://github.com/ipa320/cob_robots/pull/622/files#diff-d5e4351e5f3bc8f5fcb99475ed96d9e4R25)...thus, all robots using this file use the stuck detector..

also, as found yesterday, all robot platforms seem likely to show the base_freeze bug which is detected by the stuck detector...

2017-02-21 06:45 UTC, ipa-fxm commented
In fact, this PR will be obsolete with #622

2017-02-21 07:08 UTC, ipa-mdl commented
Yes, don't merge this.

2017-03-10 15:11 UTC, merged

2017-03-10 15:48 UTC, ipa-mdl commented
Why?

2017-03-10 15:56 UTC, ipa-fmw commented
accidentally merged this while merging the enable/disable head branches. is reverted in https://github.com/ipa320/cob_robots/commit/12e46706c6ef4b9c112b9f49852b5f16ceb0bfee