rename parameter
ipa320/cob_robots pull request #619
Opened 2017-02-13 17:29 UTC by ipa-fxm

parameter renaming in https://github.com/ipa320/cob_control/pull/133

2017-02-14 13:30 UTC, floweisshardt submitted a review, later dismissed

2017-02-15 10:14 UTC, ipa-fxm commented
Do not merge without https://github.com/ipa320/cob_control/pull/133

2017-02-16 10:42 UTC, benmaidel requested changes

2017-02-16 10:42 UTC, ipa-bnm commented on cob_hardware_config/cob4-2/config/velocity_smoother.yaml
> +safe_factor: 2.5        #used if no velocity commands received (eg. no deadman on joystick)
Why the change? This factor should only be applied on deceleration.

2017-10-31 07:22 UTC, ipa-rmb commented
Is this still relevant or can be closed?

2018-04-23 06:27 UTC, ipa-fxm commented
not in the focus anymore

2018-04-23 06:27 UTC, closed without merging