changes for using fake docking and power usage
ipa320/cob_robots pull request #624
Opened 2017-02-21 15:14 UTC by souravran

2017-02-21 16:25 UTC, fmessmer requested changes

2017-02-21 16:25 UTC, ipa-fxm commented on cob_bringup/tools/docker_control.launch
> +	</node>
can we use single line notation?
`<node if="$(arg sim)" pkg="cob_docker_control" type="fake_docking.py" name="fake_docker_control" respawn="false" output="screen" />`

2017-02-21 16:25 UTC, ipa-fxm commented on cob_bringup/tools/docker_control.launch
>  	</node>
This node does not exist anymore...what happened to it?

2017-02-21 16:25 UTC, ipa-fxm commented on cob_bringup/tools/docker_control.launch
> +	</node>
Not sure, but does any of the other nodes than need a `unless="$(arg sim"` tag?

2017-02-21 17:59 UTC, souravran commented on cob_bringup/tools/docker_control.launch
>  	</node>
I had the same question but my best guess is that the node may be obsolete or has been updated to ``multi_station_docker_control.py`` and was not removed from here.

2017-02-21 18:02 UTC, souravran commented on cob_bringup/tools/docker_control.launch
> +	</node>
Even I am not sure about the ``unless="$(arg sim)"`` tag, simulation works fine though.

2017-02-21 18:04 UTC, ipa-fxm commented on cob_bringup/tools/docker_control.launch
>  	</node>
Do you see any error message about "Node not there"?

Please remove the node from the launch file

2017-02-21 18:08 UTC, souravran commented on cob_bringup/tools/docker_control.launch
>  	</node>
No I dont get any error. Alright.

2017-02-21 18:11 UTC, ipa-fxm commented on cob_bringup/tools/docker_control.launch
>  	</node>
There still is a `docker_control.py` in https://github.com/ipa320/cob_substitute/tree/indigo_dev/cob_docker_control/scripts, maybe it uses this one...
Do you have an overlay of `cob_substitute`?
Can you put one in your workspace and remove the `docker_control.py`? Then you should get an error....
Please provide a PR for cob_substitute where the script is removed...

In the same way, we might need to add a `fake_docking.py` to `cob_substitute`!

2017-02-21 18:21 UTC, souravran commented on cob_bringup/tools/docker_control.launch
>  	</node>
No I dont have cob_substitute, will open an PR after testing with cob_substitute overlay.

2017-02-22 15:34 UTC, ipa-fxm commented
@ipa-fmw 
Do we need to `unless=$(arg sim)` the `multi_station_docker_control.py`?
(What's the purpose of this file anyway?)

@souravran 
PR to `cob_substitue` still missing

2017-02-23 21:05 UTC, ipa-fmw commented
we typically use multi_docking, which can dock e.g. to the charging station and the travel box. This works too for simulation (together with fake_docking providing correct power_state), so no need for `arg sim` in multi_docking.
But we still need `arg sim` for fake_docking

2017-03-02 07:24 UTC, fmessmer approved these changes
cob_substitute has been updated: https://github.com/ipa320/cob_substitute/pull/43

2017-03-03 08:04 UTC, merged