Setup cob4 paul stuttgart
ipa320/cob_robots pull request #634
Opened 2017-03-14 16:12 UTC by ipa-nhg

- paul configuration for cob4-7 
 - remove cob4-10 robot,not needed (this was cob4-7 with arms)

2017-03-14 16:12 UTC, ipa-nhg commented
This PR is connected to https://github.com/ipa320/cob_calibration_data/pull/128 and https://github.com/ipa320/cob_supported_robots/pull/3

2017-03-14 17:00 UTC, ipa-fxm commented
requires https://github.com/ipa320/cob_supported_robots/pull/3
requires https://github.com/ipa320/cob_calibration_data/pull/128

one more reason, why we need to proceed with #622 soon :wink:

2017-03-16 15:36 UTC, fmessmer requested changes
missed a few spots...

2017-03-16 15:36 UTC, ipa-fxm commented on cob_default_robot_behavior/scripts/trigger_srvs_cob4-7.py
>      return TriggerResponse(True, "")
cob4-7 has no arms (for the time being)..remove `pick_cb` (is buggy anyway)

2017-03-16 15:36 UTC, ipa-fxm commented on cob_default_robot_behavior/scripts/trigger_srvs_cob4-7.py
> +    s = rospy.Service('/behavior/pick', Trigger, pick_cb)
remove pick

2017-03-16 15:36 UTC, ipa-fxm commented on cob_hardware_config/cob4-7/config/diagnostics_analyzers.yaml
> +#        contains: 'head/'
remove bms, sensorring and head from this file

2017-03-16 15:36 UTC, ipa-fxm commented on cob_hardware_config/cob4-7/config/joint_state_publisher.yaml
> +source_list: [/base/joint_states, /torso/joint_states, /sensorring/joint_states, /head/joint_states]
remove sensorring and head

2017-03-16 15:36 UTC, ipa-fxm commented on cob_hardware_config/cob4-7/config/teleop.yaml
> +#    joint_velocity: [0.05]
remove sensorring?

2017-03-16 15:36 UTC, ipa-fxm commented on cob_hardware_config/cob4-7/config/teleop.yaml
>  sensorring_sss_default_target_button: 3
remove sensorring?

2017-03-16 15:36 UTC, ipa-fxm commented on cob_hardware_config/cob4-7/config/teleop.yaml
>  sensorring_joint1_button: 1
remove sensorring?

2017-03-16 16:25 UTC, fmessmer requested changes

2017-03-16 16:25 UTC, ipa-fxm commented on cob_hardware_config/cob4-7/config/teleop.yaml
> +#  }
now there is one closing `}` missing

2017-03-16 17:25 UTC, fmessmer approved these changes

2017-03-16 18:15 UTC, ipa-fxm commented
rebased, squashed, sorted and merged via #635

2017-03-16 18:15 UTC, closed without merging