Head cam config
ipa320/cob_robots pull request #645
Opened 2017-04-04 11:42 UTC by ipa-bnm

2017-04-04 11:54 UTC, ipa-bnm commented
depends on https://github.com/ipa320/cob_calibration_data/pull/129

2017-04-04 11:55 UTC, floweisshardt requested changes

2017-04-04 11:55 UTC, ipa-fmw commented on cob_hardware_config/cob4-7/config/image_flip_params_head_cam.yaml
> +rotation_mode: 0
we should keep mode 1 here as we'd like to flip the image as soon as the torso starts bending.

2017-04-04 15:24 UTC, ipa-bnm commented
@ipa-fmw removed image_flip changes

2017-04-04 15:26 UTC, fmessmer requested changes

2017-04-04 15:26 UTC, ipa-fxm commented on cob_bringup/drivers/usb_camera_node.launch
> +		<param name="framerate" value="10"/>   <!-- at 2048x1536 3.6hz is maximum on hw -->
do we achieve this rate on the robot?
maybe it makes sense to move these parameters into a yaml file within `cob_hardware_config` as they are camera-specific and this is a general usb_camera_node launch file...

also the hz_monitor.yaml needs to be adjusted to the updated framerate!

2017-04-06 12:29 UTC, fmessmer approved these changes
@ipa-bnm please merge!

2017-04-07 11:16 UTC, ipa-bnm commented
Tested on HW cob4-7

2017-04-07 11:16 UTC, merged