Raw3-1 Configuration Update
ipa320/cob_robots pull request #653
Opened 2017-04-11 14:52 UTC by ipa-bfb

The robot now works with this config.

2017-04-12 10:37 UTC, fmessmer requested changes
@ipa-rmb @ipa-bfb 
once the `arm_joint_configurations.yaml` file is removed, I will squash-merge...

2017-04-12 10:37 UTC, ipa-fxm commented on cob_default_robot_config/raw3-1/arm_joint_configurations.yaml
> +joint_names: ['arm_shoulder_pan_joint', 'arm_shoulder_lift_joint', 'arm_elbow_joint','arm_wrist_1_joint', 'arm_wrist_2_joint', 'arm_wrist_3_joint']
this file needs to be at `cob_default_robot_config/robots/raw3-1/script_server/arm_joint_configurations.yaml`
there is one available already at this location which seems to be identical: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_default_robot_config/robots/raw3-1/script_server/arm_joint_configurations.yaml

thus, please remove this file from the PR

2017-04-13 12:23 UTC, fmessmer requested changes

2017-04-13 12:23 UTC, ipa-fxm commented on cob_bringup/robots/raw3-1.xml
> +			</include>
well, in that case the `X_phidget.launch` files should be removed, as they are not used!
Please also remove the obsolete `X_phidget.yaml` files in `cob_hardware_config`.

---
nit-picking: `True` -> `true`
```
<include file="$(find cob_bringup)/drivers/relayboard.launch">
	<arg name="robot" value="$(arg robot)"/>
	<arg name="sim" value="true"/>
</include>
```

2017-04-20 11:49 UTC, ipa-fxm commented
@ipa-bfb @ipa-rmb
are you able to update this PR?

2017-04-20 13:51 UTC, ipa-bfb commented
As soon as we have the new dome running @ipa-rmb will finish this PR ;)

2017-04-24 14:22 UTC, ipa-rmb commented
Are you happy with these adaptations or did I miss something?

2017-04-24 14:29 UTC, fmessmer requested changes
maybe I can have a quick look when you guys are running the robot with this feature branch in order to see whether there is any further issues during start up and basic "robot usage"
Let me know when you are working on it
@ipa-rmb @ipa-bfb

2017-04-24 14:29 UTC, ipa-fxm commented on cob_bringup/robots/raw3-1.xml
> +			</include-->
So, then just to re-confirm: 
 - `raw3-1` indeed does not have **any** phidget-sensor onboard
 - and the robot still works for you with these lines commented out?

If both questions are answered `yes`, then you could also remove the lines completely :wink:

2017-04-25 09:23 UTC, ipa-rmb commented
we tested with the robot - it works well

2017-04-25 10:47 UTC, fmessmer approved these changes
finalized together with @ipa-rmb

2017-04-25 11:31 UTC, merged