Added a launch file to display a urdf.xacro model
ipa320/cob_robots pull request #658
Opened 2017-04-20 11:33 UTC by ipa-nhg

2017-04-20 11:42 UTC, fmessmer reviewed
some comments

2017-04-20 11:42 UTC, ipa-fxm commented on cob_hardware_config/CMakeLists.txt
> +install(FILES xacrodisplay.launch
better name `display_robot.launch`?
(you could also combine the two `FILES` install tags...

2017-04-20 11:42 UTC, ipa-fxm commented on cob_hardware_config/xacrodisplay.launch
> +<?xml version="1.0"?>
`upload_robot.launch` uses tabs for indentation

2017-04-20 11:42 UTC, ipa-fxm commented on cob_hardware_config/xacrodisplay.launch
> +  <arg name="rvizconfig" default="$(find urdf_tutorial)/urdf.rviz" />
these introduces an `exec_depend>` to `urdf_tutorial`...
how about copying that file...or simply use `cob_hardware_config/robots/$(arg robot)/$(arg robot).rviz` (should be fine enough having a RobotModel loaded to the displays...

2017-04-20 11:42 UTC, ipa-fxm commented on cob_hardware_config/xacrodisplay.launch
> +  <arg name="gui" default="false" />
default `true`?

2017-04-20 11:55 UTC, ipa-nhg commented on cob_hardware_config/xacrodisplay.launch
> +  <arg name="rvizconfig" default="$(find urdf_tutorial)/urdf.rviz" />
the `cob_hardware_config/robots/$(arg robot)/$(arg robot).rviz` includes the cameras, the sensors data, map... all of this is not needed for the purpose of the file. I propose copy the file to `cob_hardware_config/robots/common/display_robot.rviz`, is this ok?

2017-04-20 11:57 UTC, ipa-nhg commented on cob_hardware_config/xacrodisplay.launch
> +  <arg name="gui" default="false" />
I prefer false, I only use the gui modus to check the limits...

2017-04-21 06:26 UTC, fmessmer requested changes

2017-04-21 06:26 UTC, ipa-fxm commented on cob_hardware_config/display_robot.launch
> +	<arg name="rvizconfig" default="$(find cob_hardware_config)/robots/config/display_robot.rviz" />
the path of the file is `robots/common`!

2017-04-21 07:26 UTC, ipa-fmw commented on cob_hardware_config/xacrodisplay.launch
> +  <arg name="rvizconfig" default="$(find urdf_tutorial)/urdf.rviz" />
I vote for using the existing rviz configs. it does not hurt if there are laser scanners and cameras defined in the config. if we introduce a new rviz config thats one more file we have to maintain without gaining mayor benefits.

2017-04-21 07:27 UTC, floweisshardt requested changes
I vote for using the existing rviz configs. it does not hurt if there are laser scanners and cameras defined in the config. if we introduce a new rviz config thats one more file we have to maintain without gaining mayor benefits.

2017-04-21 12:11 UTC, fmessmer approved these changes

2017-04-21 12:12 UTC, ipa-fxm commented
I leave it to @ipa-fmw and @ipa-nhg to decide about the config and then merge this PR...I'm ok with both options...

2017-04-21 12:59 UTC, ipa-fmw commented
@ipa-nhg: let's fight :-)

2017-04-24 10:56 UTC, floweisshardt approved these changes

2017-04-24 10:56 UTC, merged