raw3 3 canopen
ipa320/cob_robots pull request #661
Opened 2017-04-26 14:06 UTC by ipa-fxm

this PR migrates `raw3-3` base to `ros_canopen`
see #422 

thanks @ipa-jba and @ipa-mdl for doing this!

2017-04-26 14:19 UTC, ipa-fxm commented
@destogl @andreeatulbure 
this might be of interest for you as we made some consistency changes within the (raw3-common) raw3_base_driver.yaml file which is also used on your `raw3-5`
Could you quickly test this branch and let us know whether it works for you? Thanks

2017-04-26 15:29 UTC, ipa-fxm commented
we need to make the `steer_ctrl` parameters of the `cob_omni_drive_controller/WheelController` robot-specifc:
for raw3-3 they previously have been set to
```
    steer_ctrl: # Parameters for tuning Impedance-Controller
      spring: 15.0 #10.0
      damp: 2.75 #2.5
      virt_mass: 0.1 #0.1
      d_phi_max: 12.0 #100.0
      dd_phi_max: 40.0 #100.0
```


but in `raw3_base_controller.yaml` they are now:
```
     steer_ctrl: # Parameters for tuning Impedance-Controller
       spring: 9.5
       damp: 2.25
       virt_mass: 0.1 
       d_phi_max: 12.0 #100.0
dd_phi_max: 40.0 #100.0
```

2017-04-26 15:37 UTC, ipa-mdl commented
Three options:
1. try to make them the same
2. Split config (upload additional params in `raw3_base.launch`)
3. separate config (with [controller_yaml](https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/components/raw3_base.launch#L10) arg)

2017-04-26 16:02 UTC, ipa-fxm commented
@ipa-jba will post a few comments about the steps to-be-done in #422

2017-04-27 07:08 UTC, ipa-jba commented
see https://github.com/ipa320/cob_robots/issues/422#issuecomment-297630074

2017-04-27 07:54 UTC, ipa-fxm commented
@ipa-jba 
I added another commit that should handle the control parameter missmatch between raw3-3 and raw3-5
please retest

2017-04-27 08:28 UTC, ipa-fxm commented
The parameter handling did not fully solve the oscillation....we'll do an evaluation analogue to https://github.com/ipa320/cob_control/issues/143

2017-04-27 12:51 UTC, ipa-jba commented
Right now the base starts to oscillate on the drive wheels. See the attached screenshot (shown is a rotation, where oscillation is more visible, but not exclusive)
![screenshot from 2017-04-27 14 43 57](https://cloud.githubusercontent.com/assets/2291652/25484085/cc688bd2-2b58-11e7-990e-92987cd7881b.png)

This is only reproducible if the base is on the floor (not hanging)

2017-04-27 13:40 UTC, ipa-fxm commented
according to @ipa-tif this is due to hitting an resonance frequency with the drive wheels working against the springs. a similar behavior has been observed on cob4 with loosely tuned elmo controllers

thus, it is **not** an issue of `ros_canopen` and/or configuration but an issue of the internal elmo controller configuration.

next step would be to investigate to what extend the elmo controllers can be tuned
the old elmo configuration laptop is put on `raw3-3` - and either @ipa-tif or @ipa-bdw are able to check this

2017-04-27 13:47 UTC, ipa-fxm commented
Another issue was with emergency stop being triggered which required modifications in `ros_canopen` see https://github.com/ros-industrial/ros_canopen/pull/234

2017-05-06 12:19 UTC, ipa-fxm commented
@ipa-mdl ready for final review
@ipa-jba @ipa-mig ready for final test (note: this branch is rebased...use `git checkout -B raw3-3_canopen origin-fxm/raw3-3_canopen`)

I'll merge once I get your approvals

2017-05-08 11:50 UTC, mathias-luedtke requested changes

2017-05-08 11:50 UTC, ipa-mdl commented on cob_bringup/drivers/canopen_402.launch
> +		<param name="reset_errors_before_recover" value="$(arg reset_errors_before_recover)"/>
this does not belong here

2017-05-08 11:50 UTC, ipa-mdl commented on cob_bringup/components/ros_control_base.launch
> +	<rosparam unless="$(arg sim)" ns="$(arg component_name)/driver" command="load" file="$(arg driver_yaml)"/>
This is the right place, I don't know why it was below beforehand.
It might break other robots with outdated configs..

2017-05-08 11:50 UTC, ipa-mdl commented on cob_bringup/robots/raw3-3.xml
> +			<arg name="can_device" value="can0" />
`can0` is the default

2017-05-08 11:50 UTC, ipa-mdl commented on cob_bringup/robots/raw3-5.xml
> +		<rosparam ns="base/driver" command="load" file="$(find cob_hardware_config)/robots/$(arg robot)/config/base_controller.yaml"/>
This looks wrong, controller config should go into `base` namespace

2017-05-08 11:50 UTC, ipa-mdl commented on cob_hardware_config/robots/raw3-5/config/base_controller.yaml
> +      virt_mass: 0.1
the last three could be omited, since the are same as in the default config

2017-05-08 13:00 UTC, ipa-fxm commented on cob_hardware_config/robots/raw3-5/config/base_controller.yaml
> +      virt_mass: 0.1
let's keep the parameters together...

2017-05-08 13:45 UTC, ipa-fxm commented
I considered @ipa-mdl's comments and tested this branch (including https://github.com/ros-industrial/ros_canopen/pull/234) onc `cob4-9`...works as expected

I will do a final test with @ipa-jba on `raw3-3` to clarify https://github.com/ipa320/cob_robots/pull/661#discussion_r115229481

2017-05-08 14:34 UTC, ipa-mdl commented
merged the reset feature.

2017-05-08 15:45 UTC, ipa-fxm commented on cob_bringup/robots/raw3-3.xml
> +			<arg name="can_device" value="can0" />
but the argument is requires...

2017-05-08 15:46 UTC, merged