Setup cob4-9
ipa320/cob_robots pull request #663
Opened 2017-04-27 07:41 UTC by ipa-nhg

This PR requires: https://github.com/ipa320/cob_supported_robots/pull/4 and https://github.com/ipa320/cob_calibration_data/pull/130

2017-04-27 16:02 UTC, fmessmer requested changes

2017-04-27 16:02 UTC, ipa-fxm commented on cob_bringup/robots/cob4-9.xml
> +			<arg name="fake_diagnostics" value="'base_laser_front, base_laser_right, base_laser_left, -b1, -t1, -t2, -t3, -s1, -h1, joy, safety'"/>
remove fake_diagnostics for `-t1, -t2, -t3, -s1, -h1`

2017-04-27 16:02 UTC, ipa-fxm commented on cob_default_robot_config/robots/cob4-9/base_configurations.yaml
> +service_ns: /base/driver
please obey new structure, i.e. move yaml files to `script_server` subfolder

2017-04-27 16:02 UTC, ipa-fxm commented on cob_default_robot_config/robots/cob4-9/command_gui_buttons.yaml
> +#group:
please obey new structure, i.e. move yaml files to `script_server` subfolder

2017-04-27 16:02 UTC, ipa-fxm commented on cob_default_robot_config/robots/cob4-9/upload_param_cob4-9.launch
> +	<rosparam command="load" ns="/script_server/base" file="$(find cob_default_robot_config)/robots/cob4-9/base_configurations.yaml"/>
please obey new structure, i.e. adjust to yaml files being in `script_server` subfolder

2017-04-27 16:02 UTC, ipa-fxm commented on cob_hardware_config/robots/cob4-9/config/scan_unifier_config.yaml
> +loop_rate: 100.0
`loop_rate` is no longer a parameter needed by the `scan_unifier` (https://github.com/ipa320/cob_driver/pull/324/files#diff-4b8c9c7e0bb817a56030c63677f60462L96)
we should remove it for all robots

2017-04-27 16:02 UTC, ipa-fxm commented on cob_hardware_config/robots/cob4-9/urdf/properties.urdf.xacro
> +	<!-- upper robot calibration -->
remove all `property` tags below...

2017-05-02 14:54 UTC, fmessmer approved these changes

2017-05-02 14:55 UTC, ipa-fxm commented
I rebased and finalized this PR
@ipa-fmw please test again on cob4-9 hardware according to https://github.com/ipa320/cob4/issues/297#issuecomment-297689933

2017-05-08 07:08 UTC, ipa-nhg commented
thanks @ipa-fxm your changes look good to me, tested? can be merged?

2017-05-08 13:47 UTC, fmessmer approved these changes
successfully tested on `cob4-9` again...works...

2017-05-08 13:47 UTC, merged