Update cob4-5 setup
ipa320/cob_robots pull request #666
Opened 2017-05-11 11:09 UTC by ipa-nhg

2017-05-11 11:20 UTC, ipa-fmw commented on cob_bringup/components/cam3d_sick_visionary.launch
> +<?xml version="1.0"?>
we should call this file `..._visionary_t.launch`, same as in drivers

2017-05-11 11:34 UTC, fmessmer requested changes
few remarks

2017-05-11 11:34 UTC, ipa-fxm commented on cob_bringup/components/cam3d_sick_visionary.launch
> +	<include file="$(find cob_bringup)/drivers/sick_visionary_t.launch">
add an `unless="$(arg sim)"` for the driver as in https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/components/cam3d_openni2.launch#L13

2017-05-11 11:34 UTC, ipa-fxm commented on cob_bringup/robots/base_solo.launch
> +                <arg name="robot" value="$(arg robot)"/>
use tabs

2017-05-11 11:34 UTC, ipa-fxm commented on cob_bringup/robots/cob4-5.xml
>  				<arg name="name" value="sensorring_cam3d_front"/>
pass sim argumetn `<arg name="sim" value="$(arg sim)"/>`

2017-05-11 11:34 UTC, ipa-fxm commented on cob_bringup/robots/cob4-5.xml
> +			<arg unless="$(arg sim)" name="rotation" value="0"/>
`<arg unless="$(arg sim)" name="rotation" value="270"/>` is used for the other robots
does this apply to `cob4-5` as well?

2017-05-11 11:35 UTC, ipa-fxm commented
did you test simulation with this branch?

2017-05-11 12:15 UTC, ipa-nhg commented on cob_bringup/robots/cob4-5.xml
> +			<arg unless="$(arg sim)" name="rotation" value="0"/>
No, paul has other configuration

2017-05-11 12:15 UTC, ipa-nhg commented
@ipa-fxm no, still not tested on simulation

2017-05-18 11:49 UTC, ipa-fxm commented
add updated SRDF to this PR

2017-05-18 11:50 UTC, fmessmer approved these changes

2017-05-18 11:50 UTC, fmessmer requested changes
- add updated SRDF to this PR
 - enable collision_monitor
 - test simulation

2017-05-18 13:06 UTC, ipa-nhg commented
Already tested on simulation and it is working, just there is a conflict with the coordinate system and topics of the sick_3dcs , has to be discussed https://github.com/ipa320/cob_robots/issues/669 , any way this affects to cob_description (probably the file https://github.com/ipa320/cob_common/blob/indigo_dev/cob_description/urdf/sensors/sick_3dcs.gazebo.xacro) had nothing to do with cob_robots.

The collision monitor will only be enable if it works, I prefer open a separate pull request if https://github.com/ipa320/cob4/issues/480 is solved.

Please merge this pull request if there isn't any other issue with the proposed changes. I would like to clean the robot workspace using the current upstream ipa320/indigo_dev branches.

2017-05-19 11:08 UTC, fmessmer submitted a review, later dismissed
the rest is fine

2017-05-19 11:08 UTC, ipa-fxm commented on cob_default_robot_config/robots/cob4-5/script_server/command_gui_buttons.yaml
> -    [back_down,move,back_down],
we also should remove the configs from `cob_default_robot_config/robots/cob4-5/script_server/ 	head_joint_configurations.yaml`

2017-05-22 06:35 UTC, ipa-nhg commented
I would like to keep the position, because it is a default position. We remove the button because a move between front_down and back_down could produce a collision between the head and the arms. 

For the arms we are doing the same, we define the default position "ship" but we are not including the button on the command_gui , because move from side or folded to ship in not safe, but the position is needed.

2017-05-22 08:53 UTC, floweisshardt approved these changes

2017-05-22 08:56 UTC, ipa-fmw commented
keeping the position in cob_default_robot_config is fine for me. As long as somebody knows how to prevent collission it's ok to use the default positions. where as non-skilled people should not be able to produce collissions by pressing random buttons on the dashboard

2017-05-22 08:56 UTC, merged