setup cob4-8
ipa320/cob_robots pull request #674
Opened 2017-06-07 12:09 UTC by ipa-nhg

2017-07-03 14:11 UTC, ipa-fxm commented
from https://github.com/ipa320/cob_calibration_data/pull/131#issuecomment-308479607:
 > I'll start merging cob4-8 PRs

 - https://github.com/ipa320/cob_calibration_data/pull/131 - merged

Why wait for merging the others?
 - https://github.com/ipa320/cob_supported_robots/pull/5
 - #674

2017-07-03 14:43 UTC, ipa-fmw commented
no need to wait. robot is setup and working well. let's merge

2017-07-03 18:46 UTC, fmessmer requested changes

2017-07-03 18:46 UTC, ipa-fxm commented on cob_default_robot_behavior/scripts/trigger_srvs_cob4-8.py
> +#!/usr/bin/python
https://travis-ci.org/ipa320/cob_robots/jobs/240757407#L3205

install tag is missing for cob4-8 in https://github.com/ipa-nhg/cob_robots/blob/f25d19d215aae7ce4c99369478d5a37d10e68d21/cob_default_robot_behavior/CMakeLists.txt#L10-L14

2017-07-04 07:40 UTC, fmessmer approved these changes

2017-07-04 07:40 UTC, merged