Merge with stomp config
ipa320/cob_robots pull request #675
Opened 2017-06-30 14:51 UTC by ipa-mjp

2017-07-03 13:41 UTC, fmessmer requested changes

2017-07-03 13:41 UTC, ipa-fxm commented on cob_bringup/robots/raw3-1-calib.launch
> +<launch>
what's the difference between ```raw3-1``` and ```raw3-1-calib```?
there should only be one setup for each physically existing robot

2017-07-03 13:41 UTC, ipa-fxm commented on cob_bringup/robots/raw3-1-calib.xml
> +<?xml version="1.0"?>
what's the difference between ```raw3-1``` and ```raw3-1-calib```?
there should only be one setup for each physically existing robot

2017-07-03 13:41 UTC, ipa-fxm commented on cob_hardware_config/robots/raw3-1/config/arm_modern_controller.yaml
> +   type:         force_torque_sensor_controller/ForceTorqueSensorController
please add dependencies for the controller types to the ```package.xml``` as ```run_depend```

2017-07-03 13:41 UTC, ipa-fxm commented on cob_hardware_config/robots/raw3-1/config/arm_modern_controller.yaml
> +   type: position_controllers/JointTrajectoryController
please add dependencies for the controller types to the ```package.xml``` as ```run_depend```

2017-07-03 13:41 UTC, ipa-fxm commented on cob_moveit_config/robots/raw3-1/moveit/config/kinematics.yaml
> +  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
please add dependencies for the ik plugin type to the ```package.xml``` as ```run_depend```

2017-07-03 13:41 UTC, ipa-fxm commented on cob_moveit_config/robots/raw3-1/moveit/config/kinematics.yaml
> +  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
please add dependencies for the ik plugin type to the ```package.xml``` as ```run_depend```

2017-07-04 12:27 UTC, ipa-rmb commented on cob_bringup/robots/raw3-1-calib.launch
> +<launch>
The calib can be removed, this was just a temporary setting of my student which we did not mean to add to github.

2017-07-04 12:28 UTC, ipa-rmb commented on cob_bringup/robots/raw3-1-calib.xml
> +<?xml version="1.0"?>
see above

2017-07-05 17:46 UTC, fmessmer requested changes

2017-07-05 17:46 UTC, ipa-fxm commented on cob_moveit_config/package.xml
> +  <exec_depend>trac_ik</exec_depend>
sorry, I guess the convention is to keep dependencies of `cob_moveit_config` simple...but add them to `cob_moveit_bringup`...I did this in https://github.com/ipa320/cob_manipulation/pull/116...so please remove the dependency here...sorry

2017-07-05 17:46 UTC, ipa-fxm commented on cob_moveit_config/robots/raw3-1/moveit/config/kinematics.yaml
> +  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
done in https://github.com/ipa320/cob_manipulation/pull/116

2017-07-05 17:46 UTC, ipa-fxm commented on cob_moveit_config/robots/raw3-1/moveit/config/kinematics.yaml
> +  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
done in https://github.com/ipa320/cob_manipulation/pull/116

2017-07-05 17:49 UTC, fmessmer requested changes

2017-07-05 17:49 UTC, ipa-fxm commented on cob_moveit_config/robots/raw3-1/moveit/config/constraints_limit.yaml
> +
where is this file used?
please remove this file if it was also only used for testing purposes as in *_calib...

2017-07-05 19:00 UTC, ipa-mjp commented on cob_moveit_config/robots/raw3-1/moveit/config/constraints_limit.yaml
> +
I used this file for joint constraints in ipa_order_picking_arm_planning package. I need this file.

2017-07-17 17:11 UTC, ipa-fxm commented
we won't merge this into `cob_robots` see https://github.com/ipa320/cob_robots/pull/683#issue-243463031

@ipa-mjp 
please put the respective changes into your scenatio-specific moveit_config package within `ipa_order_picking`

2017-07-17 17:11 UTC, closed without merging