[WIP] preparation for fdm test
ipa320/cob_robots pull request #677
Opened 2017-07-05 16:51 UTC by ipa-fmw

Do not merge yet. needed for test rigs

2017-07-05 17:37 UTC, ipa-fxm commented
please remove the mimic related stuff to a separate PR!

2017-07-18 05:55 UTC, ipa-fxm commented
@ipa-fmw please separate the mimic part into a standalone PR

2017-07-18 12:32 UTC, ipa-nhg commented on cob_bringup/robots/cob4-7.xml
> +		<include file="$(find cob_bringup)/drivers/mimic.launch"/>
did you change the head pc display configuration? why is the rotation not needed?

2017-08-02 07:03 UTC, ipa-fxm commented
I rebased to get rid of the mimic changes

what else needs to be done to finalize?
I guess removing the parts uploading parameters will break the driver for the robots...

2017-08-04 09:05 UTC, fmessmer requested changes
block PR for verification

2017-08-04 09:05 UTC, ipa-fxm commented on cob_bringup/drivers/canopen_402.launch
> -		<rosparam command="load" file="$(arg pkg_hardware_config)/robots/$(arg robot)/config/$(arg component_name)_driver.yaml"/>
I guess removing the parts uploading parameters will break the driver for the robots...

2017-09-06 07:53 UTC, ipa-fxm commented
@ipa-fmw 
with quite some new cob4_bases coming up...what do we need to finalize the fdm test site (hw-/sw-wise?)

2017-09-06 08:15 UTC, ipa-fmw commented
finalizing this should be done by end of August, so that we can test the FDMs which will be ready in beginning of september

... just lacking time to finalize this at the moment

2017-10-30 15:02 UTC, ipa-fxm commented
@ipa-fmw
not needed for ipa320/cob_hardware_test#11
can be  closed

2017-10-30 15:12 UTC, closed without merging