Feature/zr300 for torso cameras
ipa320/cob_robots pull request #692
Opened 2017-07-25 18:29 UTC by ipa-fmw

2017-07-26 06:10 UTC, fmessmer requested changes

2017-07-26 06:10 UTC, fmessmer commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
do you have an overlay of `realsense_camera`?
in my `/opt/ros/` I can only find a `zr300_nodelet_default.launch` file

2017-07-26 06:10 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +		<!-- static frames broadcasted by camera driver -->
the values below are for copy-pasted from `cob_bringup/components/cam3d_r200_rgbd.launch`, right?
we need to verify/get/update these transforms with a zr300!

2017-07-26 06:10 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +		<!-- relay additional topics not available from sensor plugin -->
also, the topics need to be compared between sim and hw

2017-07-26 06:10 UTC, ipa-fxm commented on cob_bringup/robots/cob4-7.xml
> +			<arg name="name" value="torso_cam3d_left"/>
why has the sides been swapped?
cam_left is now on t1 - cam_right on t3
the other robots have it the other way! can we re-plug the cameras?

2017-07-26 06:10 UTC, ipa-fxm commented on cob_bringup/robots/cob4-7.xml
>  			<arg name="sim" value="$(arg sim)"/>
this camera has not `serial_no` argument!

2017-07-26 06:10 UTC, ipa-fxm commented on cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro
> +  <xacro:include filename="$(find cob_description)/urdf/sensors/realsense_zr300.urdf.xacro" />
this file does not exist yet! the PR to cob_common is missing!

BTW, what's the difference between the two urdf descriptions? if there is none (or it is minimal), I'd prefer to have both realsense_cameras in the same xacro....(and maybe use some xacro arguments)

2017-07-26 07:57 UTC, ipa-fmw commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
yes we need an overlay. ZR300 launch files are already merged but not released again.

2017-07-26 07:58 UTC, ipa-fmw commented on cob_bringup/robots/cob4-7.xml
> +			<arg name="name" value="torso_cam3d_left"/>
this way it's more intuitive: left pc + left camera and right pc + right camera

2017-07-26 08:19 UTC, ipa-fmw commented on cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro
> +  <xacro:include filename="$(find cob_description)/urdf/sensors/realsense_zr300.urdf.xacro" />
PR in cob_common is https://github.com/ipa320/cob_common/pull/225

at the moment the files are copied. But as soon as we harmonize hw and sim, we need to add the fisheye camera and if possible the IMU which is not available on the r200

2017-07-26 08:46 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
then please add the repo to the rosinstall file for Travis CI to pass!

2017-07-26 15:31 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
this is not even an unreleased version of official `intel-ros/realsense` but a [feature branch](https://github.com/ipa-bnm/realsense/tree/fix/launch_file_rename) of `ipa-bnm/realsense` see https://github.com/intel-ros/realsense/pull/244

2017-07-26 15:33 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +		<!-- static frames broadcasted by camera driver -->
values are correct for zr300 as well
still frame_ids are wrong (not prefixed correctly by driver see https://github.com/intel-ros/realsense/issues/258

2017-07-26 17:46 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +		<!-- static frames broadcasted by camera driver -->
missing static transforms are added in ipa-fmw/cob_robots#45

2017-07-27 11:19 UTC, ipa-bnm commented on cob_bringup/robots/cob4-7.xml
>  			<arg name="sim" value="$(arg sim)"/>
right there should not be a serial_no arguemnt

2017-07-27 11:20 UTC, benmaidel submitted a review, later dismissed

2017-07-27 12:19 UTC, ipa-bnm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
added realsense to travis rosinstall

2017-07-27 12:19 UTC, ipa-bnm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +		<!-- static frames broadcasted by camera driver -->
already merged!

2017-07-27 12:21 UTC, benmaidel submitted a review, later dismissed

2017-07-27 13:57 UTC, ipa-fmw commented
@ipa-fxm: please review again

2017-07-27 14:03 UTC, ipa-bnm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
If we like to release cob_robots we should fall back to the typo rgdb, so we can use the released realsense package.

2017-07-27 14:24 UTC, ipa-fxm commented
@ipa-jba @ipa-rmb @ipa-fez FYI
this is "being admin" at it's finest :wink:

2017-07-27 14:28 UTC, ipa-fxm commented on cob_bringup/components/cam3d_zr300_rgbd.launch
> +	<include unless="$(arg sim)" file="$(find realsense_camera)/launch/zr300_nodelet_rgbd.launch">
even with switching back to rg**db** launch file...this is not yet released...in the current release of `realsense_camera` there is only a `zr300_nodelet_default.launch` file for the zr300

2017-07-28 08:29 UTC, jabbenseth requested changes
until intel-ros/realsense#244 is merged and released

2017-07-31 07:00 UTC, ipa-fxm commented
a fix for the issue with the optical frame prefixing (intel-ros/realsense#258) is proposed in intel-ros/realsense#259

2017-09-06 07:46 UTC, ipa-fxm commented
rebase in #715

2017-09-21 20:26 UTC, ipa-fxm commented
closing in favor of #715

2017-09-21 20:26 UTC, closed without merging