remove cob_trajectory_controller
ipa320/cob_robots pull request #695
Opened 2017-07-31 08:30 UTC by ipa-fmw

- fixes parts of https://github.com/ipa320/care-o-bot/issues/46

2017-07-31 08:42 UTC, ipa-fxm commented
raw3-1 still uses it: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/robots/raw3-1.xml#L57-L61

2017-07-31 08:43 UTC, fmessmer requested changes
do not merge
raw3-1 still uses it: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/robots/raw3-1.xml#L57-L61

2017-07-31 09:12 UTC, ipa-fmw commented
good catch. what do we have to do to get rid of that dependency?
@brinup-push (@ipa-rmb, @ipa-jba, @ipa-fez)

2017-08-14 15:56 UTC, ipa-rmb commented
This should be fixed by #708 by now.

2017-08-15 15:42 UTC, ipa-fxm commented
removing obsolete launch files and reapective dependencies is tracked in#703

2017-08-15 15:42 UTC, ipa-fxm commented
removing obsolete launch files and reapective dependencies is tracked in#703

2017-09-06 06:48 UTC, ipa-fxm commented
properly removed in #714

2017-09-06 06:48 UTC, closed without merging