changes for cob4-13
ipa320/cob_robots pull request #756
Opened 2018-04-23 16:04 UTC by HannesBachter

2018-04-23 16:27 UTC, fmessmer requested changes
as the head is fixed, plz remove all `head_*.yaml` in `cob_hardware_config/robots/cob4-13/config`

2018-04-23 16:27 UTC, ipa-fxm commented on cob_bringup/robots/cob4-16.xml
> +			<arg name="can_device" value="can3"/>
`cob4-16` has been shipped
thus, please undo these changes

2018-04-23 16:27 UTC, ipa-fxm commented on cob_hardware_config/robots/cob4-13/urdf/cob4-13.urdf.xacro
> +  <xacro:include filename="$(find cob_description)/urdf/sensors/kinect.urdf.xacro" />
remove this line - there is no kinect mounted to the robot

2018-04-26 11:33 UTC, fmessmer approved these changes
@HannesBachter 
I added a few commits to fix my remarks...I also tested the simulation (had to add the gripper part again for cob4-13 and cob4-16)

Please test again on HW after @ipa-tif fixed the HW-Issues

2018-04-27 08:10 UTC, HannesBachter commented
tested on HW - works as expected

2018-04-27 08:17 UTC, merged

2018-04-27 08:18 UTC, fmessmer commented
I merged in order to start playing back the config improvements from unity_robots