raw-mini added
ipa320/cob_robots pull request #773
Opened 2019-01-17 11:24 UTC by ipa-fke-fs

An addition to the PR ipa320/ipa_navigation_sandbox#349 and https://github.com/ipa320/ipa_navigation_sandbox/pull/350

2019-01-24 08:10 UTC, pschnattinger approved these changes

2019-01-30 21:26 UTC, fmessmer requested changes
- add `raw-mini` to `cob_supported_robots` to activate CI checks
- launch files missing
- meshes and macros for urdf missing -> `cob_common`

2019-01-30 21:27 UTC, fmessmer commented
also, how is this different from #752?
please sync!

2019-02-07 07:01 UTC, ipa-fke-fs commented
@fmessmer there is no difference except for the cob4-13. I have't seen this PR which can also be used. So I will close this PR.

2019-02-07 07:05 UTC, closed without merging