Add cob4 23
ipa320/cob_robots pull request #799
Opened 2020-02-05 13:46 UTC by HannesBachter

needs https://github.com/ipa320/cob_navigation/pull/114
needs https://github.com/ipa320/cob_calibration_data/pull/163

2020-02-05 14:12 UTC, fmessmer requested changes
PR for `cob_supported_robots` is missing

2020-02-05 16:03 UTC, HannesBachter commented
PR for `cob_supported_robots` is here: https://github.com/ipa320/cob_supported_robots/pull/26

2020-02-05 18:05 UTC, fmessmer requested changes

2020-02-05 18:05 UTC, fmessmer commented on cob_moveit_config/robots/cob4-23/moveit/.setup_assistant
> +    relative_path: config/cob4-22.srdf
use cob4-23

2020-02-05 18:05 UTC, fmessmer commented on cob_moveit_config/robots/cob4-23/moveit/config/cob4-23.srdf
> +<robot name="cob4-2333">
use cob4-23

2020-02-06 18:46 UTC, fmessmer approved these changes

2020-02-06 18:46 UTC, merged