corrected cameras for cob4-7 urdf
ipa320/cob_robots pull request #819
Opened 2021-11-18 08:02 UTC by ipa-foj

- addresses #818
 - adapting camera descriptions in cob4-7 urdf

2021-11-18 10:33 UTC, fmessmer requested changes
the `realsense_d435` macro has different xacros args than the `realsense_zr300` xacro
```
$ ( source /root/upstream_ws/install/setup.bash && cd /root/target_ws && catkin_test_results --verbose; )

Full test results for 'build/cob_hardware_config/test_results/cob_hardware_config/roslaunch-check_upload_robot__robot_cob4-7.launch.xml'

-------------------------------------------------

<testsuite errors="0" failures="1" name="roslaunch-check_upload_robot__robot_cob4-7.launch.xml" tests="1" time="1"><testcase classname="roslaunch.RoslaunchCheck" name="cob_hardware_config_upload_robot_launch" status="run" time="1"><failure message="roslaunch check [/root/target_ws/src/cob_robots/cob_hardware_config/upload_robot.launch] failed" type="" /></testcase><system-out>&lt;![CDATA[

[/root/target_ws/src/cob_robots/cob_hardware_config/upload_robot.launch]:

	Invalid &lt;param&gt; tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro --inorder '/root/target_ws/src/cob_robots/cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro'] returned with code [2]. 

Param xml is &lt;param command="$(find xacro)/xacro --inorder '$(arg pkg_hardware_config)/robots/$(arg robot)/urdf/$(arg robot).urdf.xacro'" name="robot_description"/&gt;

]]&gt;</system-out></testsuite>

-------------------------------------------------

Full test results for 'build/cob_hardware_config/test_results/cob_hardware_config/rosunit-cob4-7_test.xml'

-------------------------------------------------

<?xml version="1.0" encoding="utf-8"?>

<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="1.322"><testcase classname="__main__.TestUrdf" name="test_correct_format" time="1.3219"><failure type="AssertionError">cannot convert xacro. file: /root/target_ws/src/cob_robots/cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro

Output: 

Error: error: Invalid parameter "ros_topic" None None

when instantiating macro: realsense_d435 (/root/upstream_ws/install/share/cob_description/urdf/sensors/realsense_d435.urdf.xacro)

in file: /root/target_ws/src/cob_robots/cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro

  File "/usr/lib/python2.7/unittest/case.py", line 329, in run

    testMethod()

  File "/root/upstream_ws/install/lib/cob_description/test_urdf.py", line 47, in test_correct_format

    self.fail("cannot convert xacro. file: " + file_to_test + "\nOutput: " + out + "\nError: " + err)

  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail

    raise self.failureException(msg)

</failure></testcase><system-out>&lt;![CDATA[

['/root/upstream_ws/install/lib/cob_description/test_urdf.py', '/root/target_ws/src/cob_robots/cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro', '--gtest_output=xml:/root/target_ws/build/cob_hardware_config/test_results/cob_hardware_config/rosunit-cob4-7_test.xml', '__name:=cob4-7_test', '__log:=/root/.ros/log/33287cda-4849-11ec-8355-0242ac110002/cob4-7_test-1.log']

5

testing /root/target_ws/src/cob_robots/cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro

]]&gt;</system-out><system-err>&lt;![CDATA[

]]&gt;</system-err></testsuite>

-------------------------------------------------

Full test results for 'build/cob_bringup/test_results/cob_bringup/roslaunch-check_robots_cob4-7.xml.xml'

-------------------------------------------------

<testsuite errors="0" failures="1" name="roslaunch-check_robots_cob4-7.xml.xml" tests="1" time="1"><testcase classname="roslaunch.RoslaunchCheck" name="cob_bringup_robots_cob4-7_xml" status="run" time="1"><failure message="roslaunch check [/root/target_ws/src/cob_robots/cob_bringup/robots/cob4-7.xml] failed" type="" /></testcase><system-out>&lt;![CDATA[

[/root/target_ws/src/cob_robots/cob_bringup/robots/cob4-7.xml]:

	while processing /root/target_ws/install/share/cob_hardware_config/upload_robot.launch:

Invalid &lt;param&gt; tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro --inorder '/root/target_ws/install/share/cob_hardware_config/robots/cob4-7/urdf/cob4-7.urdf.xacro'] returned with code [2]. 

Param xml is &lt;param command="$(find xacro)/xacro --inorder '$(arg pkg_hardware_config)/robots/$(arg robot)/urdf/$(arg robot).urdf.xacro'" name="robot_description"/&gt;

]]&gt;</system-out></testsuite>

-------------------------------------------------

build/cob_bringup/test_results/cob_bringup/roslaunch-check_robots_cob4-7.xml.xml: 1 tests, 0 errors, 1 failures, 0 skipped

build/cob_hardware_config/test_results/cob_hardware_config/roslaunch-check_upload_robot__robot_cob4-7.launch.xml: 1 tests, 0 errors, 1 failures, 0 skipped

build/cob_hardware_config/test_results/cob_hardware_config/rosunit-cob4-7_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped

Summary: 96 tests, 0 errors, 3 failures, 0 skipped

The command ".industrial_ci/travis.sh" exited with 1.
```

2021-11-18 10:35 UTC, fmessmer requested changes
also, the mount point of the different realsense are different....please check with `roslaunch cob_hardware_config display_robot.launch robot:=cob4-7` 

and verify the cameras are mounted as they are on the real robot....if they are not you'll have to adjust the calibration_default.xacro of cob4-7 to translate and rotate the cameras accordingly

2021-11-18 14:01 UTC, ipa-foj commented
Adapted the args corresponding to the `realsense_d435` urdf.

Also checked the mounting of the cameras, they seem to be mounted as in reality.

2021-11-19 13:25 UTC, fmessmer approved these changes

2021-11-19 13:26 UTC, merged